[package]
name = "fem_stiffness"
version = "0.1.0"
edition = "2021"

[dependencies]
fenris = "0.0.33"
fenris-solid = "0.0.33"
clap = { version="4.4.6", features = [ "derive" ] }
eyre = "0.6.8"
nalgebra-sparse = { version = "0.9.0", features = [ "io" ] }
